name: Build rootfs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TMP: '/scratch'

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    container:
      image: docker.io/godebos/debos:latest
      options: >-
        --security-opt label=disable
        --cap-add=SYS_PTRACE
        --tmpfs /scratch:exec
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'cazou/cros-codecs-ci'
      - name: Create output directory
        run: mkdir out
      - name: Build rootfs
        run: cd out && debos --print-recipe -v ../debos/rootfs.yaml
