name: Run LAVA tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    container:
      image: docker.io/godebos/debos:latest
      volumes:
        - /home/runner/work:/recipe
      options: "-w /recipes --security-opt label=disabled --cap-add=SYS_PTRACE --cap-add=SYS_ADMIN"
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'cazou/cros-codecs-ci'
#   - name: Install dependencies
#     run: sudo apt-get install user-mode-linux
    - name: Build rootfs
      run: debos debos/rootfs.yaml
