name: Run LAVA tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    container:
      image: docker.io/godebos/debos:latest
      volumes:
        - /home/runner/work:/recipe
      options: "-w /recipes --security-opt label=disabled --device /dev/kvm --cap-add=SYS_PTRACE --cap-add=SYS_ADMIN"
    steps:
      - name: build-rootfs
        run: debos debos/rootfs.yaml
