name: Build rootfs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TMP: '/scratch'

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt
        run: sudo apt-get update
      - name: Install kvm deps
        run: sudo apt-get install -y cpu-checker qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo apt-get update
          sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu qemu-system-x86
          sudo usermod -a -G kvm,libvirt $USER

      - uses: actions/checkout@v3
        with:
          repository: 'cazou/cros-codecs-ci'
      - name: Build rootfs
        run: "docker run --rm --security-opt label=disable --cap-add=SYS_PTRACE --cap-add=SYS_ADMIN  --device /dev/kvm --tmpfs '/scratch:exec' -e TMP:'/scratch' -w /recipe -v ${PWD}:/recipe docker.io/godebos/debos:latest --print-recipe -v --show-boot debos/rootfs.yaml"
