name: Build rootfs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TMP: '/scratch'

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt
        run: sudo apt-get update
      - name: Install kvm deps
        run: sudo apt-get install -y cpu-checker qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager
      - uses: actions/checkout@v3
        with:
          repository: 'cazou/cros-codecs-ci'
      - name: Build rootfs
        run: "docker run --rm --security-opt label=disable --cap-add=SYS_PTRACE --cap-add=SYS_ADMIN  --device /dev/kvm --tmpfs '/scratch:exec' -e TMP:'/scratch' -w /recipe -v ./:/recipe docker.io/godebos/debos:latest --print-recipe -v --show-boot debos/rootfs.yaml"
